var getdata = contract.set.getData("secu_com_0", "air.com.playtika.slotomania-223000001.apk", "game", "developer7", "Lcom/appoxee/activities/AppoxeeBaseActivity;.onNewIntent:(Landroid/content/Intent;)V", " Landroid/content/Context;.startActivity:(Landroid/content/Intent;)V 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_0", "air.com.playtika.slotomania-223000001.apk", "game", "developer7", "Lcom/appoxee/activities/AppoxeeBaseActivity;.onNewIntent:(Landroid/content/Intent;)V", " Landroid/util/Log;.e:(Ljava/lang/String;Ljava/lang/String;)I 2");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_0", "air.com.playtika.slotomania-223000001.apk", "game", "developer7", "Lcom/appoxee/activities/AppoxeeBaseActivity;.onNewIntent:(Landroid/content/Intent;)V", " Landroid/content/Context;.startActivity:(Landroid/content/Intent;)V 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_0", "air.com.playtika.slotomania-223000001.apk", "game", "developer7", "Lcom/appoxee/activities/AppoxeeBaseActivity;.onNewIntent:(Landroid/content/Intent;)V", " Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I 2");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_0", "air.com.playtika.slotomania-223000001.apk", "game", "developer7", "Lcom/appoxee/activities/AppoxeeBaseActivity;.onNewIntent:(Landroid/content/Intent;)V", " Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I 2");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_0", "air.com.playtika.slotomania-223000001.apk", "game", "developer7", "Lcom/appoxee/activities/AppoxeeBaseActivity;.onNewIntent:(Landroid/content/Intent;)V", " Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I 2");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_0", "air.com.playtika.slotomania-223000001.apk", "game", "developer7", "Lcom/appoxee/activities/AppoxeeBaseActivity;.onNewIntent:(Landroid/content/Intent;)V", " Landroid/content/Context;.startActivity:(Landroid/content/Intent;)V 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_0", "air.com.playtika.slotomania-223000001.apk", "game", "developer7", "Lcom/appoxee/activities/AppoxeeBaseActivity;.onNewIntent:(Landroid/content/Intent;)V", " Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I 2");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "air.com.sgn.cookiejam.gp-4080212.apk", "game", "developer8", "Ljava/net/URLConnection;.getInputStream:()Ljava/io/InputStream;", " Ljava/io/FileOutputStream;.write:([BII)V 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_2", "air.com.sgn.juicejam.gp-1015008.apk", "game", "developer8", "Ljava/net/URLConnection;.getInputStream:()Ljava/io/InputStream;", " Ljava/io/FileOutputStream;.write:([BII)V 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_0", "com.aim.racing-20046.apk", "game", "developer9", "Lcom/heyzap/internal/ProxyActivity;.removeStickyBroadcast:(Landroid/content/Intent;)V", " Lcom/heyzap/internal/ProxyActivity;.startActivity:(Landroid/content/Intent;)V 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_0", "com.aim.racing-20046.apk", "game", "developer9", "Lcom/heyzap/internal/ProxyActivity;.startIntentSender:(Landroid/content/IntentSender;Landroid/content/Intent;IIILandroid/os/Bundle;)V", " Lcom/heyzap/internal/ProxyActivity;.sendOrderedBroadcast:(Landroid/content/Intent;Ljava/lang/String;Landroid/content/BroadcastReceiver;Landroid/os/Handler;ILjava/lang/String;Landroid/os/Bundle;)V 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_0", "com.aim.racing-20046.apk", "game", "developer9", "Lcom/heyzap/internal/ProxyActivity;.startIntentSender:(Landroid/content/IntentSender;Landroid/content/Intent;IIILandroid/os/Bundle;)V", " Lcom/heyzap/internal/ProxyActivity;.startActivity:(Landroid/content/Intent;)V 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_0", "com.aim.racing-20046.apk", "game", "developer9", "Lcom/heyzap/internal/ProxyActivity;.removeStickyBroadcast:(Landroid/content/Intent;)V", " Lcom/heyzap/internal/ProxyActivity;.sendOrderedBroadcast:(Landroid/content/Intent;Ljava/lang/String;)V 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_0", "com.aim.racing-20046.apk", "game", "developer9", "Landroid/content/pm/PackageManager;.queryIntentServices:(Landroid/content/Intent;I)Ljava/util/List;", " Landroid/content/Context;.bindService:(Landroid/content/Intent;Landroid/content/ServiceConnection;I)Z 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_0", "com.aim.racing-20046.apk", "game", "developer9", "Lcom/heyzap/internal/ProxyActivity;.removeStickyBroadcast:(Landroid/content/Intent;)V", " Lcom/heyzap/internal/ProxyActivity;.startService:(Landroid/content/Intent;)Landroid/content/ComponentName; 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_0", "com.aim.racing-20046.apk", "game", "developer9", "Lcom/heyzap/internal/ProxyActivity;.stopService:(Landroid/content/Intent;)Z", " Lcom/heyzap/internal/ProxyActivity;.startService:(Landroid/content/Intent;)Landroid/content/ComponentName; 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_0", "com.aim.racing-20046.apk", "game", "developer9", "Lcom/heyzap/internal/ProxyActivity;.startIntentSender:(Landroid/content/IntentSender;Landroid/content/Intent;IIILandroid/os/Bundle;)V", " Lcom/heyzap/internal/ProxyActivity;.sendStickyOrderedBroadcast:(Landroid/content/Intent;Landroid/content/BroadcastReceiver;Landroid/os/Handler;ILjava/lang/String;Landroid/os/Bundle;)V 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_0", "com.aim.racing-20046.apk", "game", "developer9", "Lcom/heyzap/internal/ProxyActivity;.stopService:(Landroid/content/Intent;)Z", " Lcom/heyzap/internal/ProxyActivity;.sendStickyBroadcast:(Landroid/content/Intent;)V 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_0", "com.aim.racing-20046.apk", "game", "developer9", "Lcom/heyzap/internal/ProxyActivity;.stopService:(Landroid/content/Intent;)Z", " Landroid/app/Activity;.setResult:(ILandroid/content/Intent;)V 2");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_0", "com.aim.racing-20046.apk", "game", "developer9", "Lcom/heyzap/internal/ProxyActivity;.startIntentSender:(Landroid/content/IntentSender;Landroid/content/Intent;IIILandroid/os/Bundle;)V", " Lcom/heyzap/internal/ProxyActivity;.bindService:(Landroid/content/Intent;Landroid/content/ServiceConnection;I)Z 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_0", "com.aim.racing-20046.apk", "game", "developer9", "Lcom/heyzap/internal/ProxyActivity;.startIntentSender:(Landroid/content/IntentSender;Landroid/content/Intent;IIILandroid/os/Bundle;)V", " Lcom/heyzap/internal/ProxyActivity;.sendBroadcast:(Landroid/content/Intent;Ljava/lang/String;)V 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_0", "com.aim.racing-20046.apk", "game", "developer9", "Lcom/heyzap/internal/ProxyActivity;.startIntentSender:(Landroid/content/IntentSender;Landroid/content/Intent;IIILandroid/os/Bundle;)V", " Lcom/heyzap/internal/ProxyActivity;.sendOrderedBroadcast:(Landroid/content/Intent;Ljava/lang/String;)V 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_0", "com.aim.racing-20046.apk", "game", "developer9", "Lcom/heyzap/internal/ProxyActivity;.removeStickyBroadcast:(Landroid/content/Intent;)V", " Landroid/app/Activity;.startActivityForResult:(Landroid/content/Intent;I)V 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_0", "com.aim.racing-20046.apk", "game", "developer9", "Lcom/heyzap/internal/ProxyActivity;.stopService:(Landroid/content/Intent;)Z", " Lcom/heyzap/internal/ProxyActivity;.startActivityForResult:(Landroid/content/Intent;I)V 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_0", "com.aim.racing-20046.apk", "game", "developer9", "Lcom/heyzap/internal/ProxyActivity;.removeStickyBroadcast:(Landroid/content/Intent;)V", " Lcom/heyzap/internal/ProxyActivity;.startActivity:(Landroid/content/Intent;Landroid/os/Bundle;)V 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_0", "com.aim.racing-20046.apk", "game", "developer9", "Lcom/heyzap/internal/ProxyActivity;.startIntentSender:(Landroid/content/IntentSender;Landroid/content/Intent;IIILandroid/os/Bundle;)V", " Lcom/heyzap/internal/ProxyActivity;.sendBroadcast:(Landroid/content/Intent;)V 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_0", "com.aim.racing-20046.apk", "game", "developer9", "Lcom/heyzap/internal/ProxyActivity;.removeStickyBroadcast:(Landroid/content/Intent;)V", " Lcom/heyzap/internal/ProxyActivity;.startActivityForResult:(Landroid/content/Intent;I)V 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_0", "com.aim.racing-20046.apk", "game", "developer9", "Landroid/os/Handler;.obtainMessage:(ILjava/lang/Object;)Landroid/os/Message;", " Landroid/os/Handler;.sendMessage:(Landroid/os/Message;)Z 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_0", "com.aim.racing-20046.apk", "game", "developer9", "Lcom/heyzap/internal/ProxyActivity;.stopService:(Landroid/content/Intent;)Z", " Lcom/heyzap/internal/ProxyActivity;.startActivity:(Landroid/content/Intent;)V 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_0", "com.aim.racing-20046.apk", "game", "developer9", "Lcom/heyzap/internal/ProxyActivity;.stopService:(Landroid/content/Intent;)Z", " Lcom/heyzap/internal/ProxyActivity;.startActivityForResult:(Landroid/content/Intent;ILandroid/os/Bundle;)V 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_0", "com.aim.racing-20046.apk", "game", "developer9", "Lcom/heyzap/internal/ProxyActivity;.startIntentSender:(Landroid/content/IntentSender;Landroid/content/Intent;IIILandroid/os/Bundle;)V", " Landroid/app/Activity;.setResult:(ILandroid/content/Intent;)V 2");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_0", "com.aim.racing-20046.apk", "game", "developer9", "Lcom/heyzap/internal/ProxyActivity;.startIntentSender:(Landroid/content/IntentSender;Landroid/content/Intent;IIILandroid/os/Bundle;)V", " Lcom/heyzap/internal/ProxyActivity;.startActivity:(Landroid/content/Intent;Landroid/os/Bundle;)V 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_0", "com.aim.racing-20046.apk", "game", "developer9", "Lcom/heyzap/internal/ProxyActivity;.removeStickyBroadcast:(Landroid/content/Intent;)V", " Landroid/app/Activity;.setResult:(ILandroid/content/Intent;)V 2");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_0", "com.aim.racing-20046.apk", "game", "developer9", "Lcom/heyzap/internal/ProxyActivity;.removeStickyBroadcast:(Landroid/content/Intent;)V", " Lcom/heyzap/internal/ProxyActivity;.sendStickyBroadcast:(Landroid/content/Intent;)V 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_0", "com.aim.racing-20046.apk", "game", "developer9", "Lcom/heyzap/internal/ProxyActivity;.removeStickyBroadcast:(Landroid/content/Intent;)V", " Lcom/heyzap/internal/ProxyActivity;.sendBroadcast:(Landroid/content/Intent;)V 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_0", "com.aim.racing-20046.apk", "game", "developer9", "Lcom/heyzap/internal/ProxyActivity;.stopService:(Landroid/content/Intent;)Z", " Lcom/heyzap/internal/ProxyActivity;.bindService:(Landroid/content/Intent;Landroid/content/ServiceConnection;I)Z 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_0", "com.aim.racing-20046.apk", "game", "developer9", "Lcom/heyzap/internal/ProxyActivity;.startIntentSender:(Landroid/content/IntentSender;Landroid/content/Intent;IIILandroid/os/Bundle;)V", " Lcom/heyzap/internal/ProxyActivity;.startActivityForResult:(Landroid/content/Intent;ILandroid/os/Bundle;)V 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_0", "com.aim.racing-20046.apk", "game", "developer9", "Lcom/heyzap/internal/ProxyActivity;.stopService:(Landroid/content/Intent;)Z", " Landroid/app/Activity;.startActivityForResult:(Landroid/content/Intent;I)V 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_0", "com.aim.racing-20046.apk", "game", "developer9", "Lcom/heyzap/internal/ProxyActivity;.stopService:(Landroid/content/Intent;)Z", " Lcom/heyzap/internal/ProxyActivity;.sendBroadcast:(Landroid/content/Intent;)V 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_0", "com.aim.racing-20046.apk", "game", "developer9", "Lcom/heyzap/internal/ProxyActivity;.removeStickyBroadcast:(Landroid/content/Intent;)V", " Lcom/heyzap/internal/ProxyActivity;.startActivityForResult:(Landroid/content/Intent;ILandroid/os/Bundle;)V 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_0", "com.aim.racing-20046.apk", "game", "developer9", "Lcom/heyzap/internal/ProxyActivity;.stopService:(Landroid/content/Intent;)Z", " Lcom/heyzap/internal/ProxyActivity;.sendBroadcast:(Landroid/content/Intent;Ljava/lang/String;)V 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_0", "com.aim.racing-20046.apk", "game", "developer9", "Lcom/heyzap/internal/ProxyActivity;.stopService:(Landroid/content/Intent;)Z", " Lcom/heyzap/internal/ProxyActivity;.sendOrderedBroadcast:(Landroid/content/Intent;Ljava/lang/String;)V 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_0", "com.aim.racing-20046.apk", "game", "developer9", "Lcom/heyzap/internal/ProxyActivity;.removeStickyBroadcast:(Landroid/content/Intent;)V", " Lcom/heyzap/internal/ProxyActivity;.sendStickyOrderedBroadcast:(Landroid/content/Intent;Landroid/content/BroadcastReceiver;Landroid/os/Handler;ILjava/lang/String;Landroid/os/Bundle;)V 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_0", "com.aim.racing-20046.apk", "game", "developer9", "Lcom/heyzap/internal/ProxyActivity;.startIntentSender:(Landroid/content/IntentSender;Landroid/content/Intent;IIILandroid/os/Bundle;)V", " Landroid/app/Activity;.startActivityForResult:(Landroid/content/Intent;I)V 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_0", "com.aim.racing-20046.apk", "game", "developer9", "Lcom/heyzap/internal/ProxyActivity;.removeStickyBroadcast:(Landroid/content/Intent;)V", " Lcom/heyzap/internal/ProxyActivity;.sendBroadcast:(Landroid/content/Intent;Ljava/lang/String;)V 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_0", "com.aim.racing-20046.apk", "game", "developer9", "Lcom/heyzap/internal/ProxyActivity;.removeStickyBroadcast:(Landroid/content/Intent;)V", " Lcom/heyzap/internal/ProxyActivity;.sendOrderedBroadcast:(Landroid/content/Intent;Ljava/lang/String;Landroid/content/BroadcastReceiver;Landroid/os/Handler;ILjava/lang/String;Landroid/os/Bundle;)V 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_0", "com.aim.racing-20046.apk", "game", "developer9", "Lcom/heyzap/internal/ProxyActivity;.stopService:(Landroid/content/Intent;)Z", " Lcom/heyzap/internal/ProxyActivity;.startActivity:(Landroid/content/Intent;Landroid/os/Bundle;)V 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_0", "com.aim.racing-20046.apk", "game", "developer9", "Lcom/heyzap/internal/ProxyActivity;.startIntentSender:(Landroid/content/IntentSender;Landroid/content/Intent;IIILandroid/os/Bundle;)V", " Lcom/heyzap/internal/ProxyActivity;.startService:(Landroid/content/Intent;)Landroid/content/ComponentName; 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_0", "com.aim.racing-20046.apk", "game", "developer9", "Lcom/heyzap/internal/ProxyActivity;.stopService:(Landroid/content/Intent;)Z", " Lcom/heyzap/internal/ProxyActivity;.sendOrderedBroadcast:(Landroid/content/Intent;Ljava/lang/String;Landroid/content/BroadcastReceiver;Landroid/os/Handler;ILjava/lang/String;Landroid/os/Bundle;)V 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_0", "com.aim.racing-20046.apk", "game", "developer9", "Lcom/heyzap/internal/ProxyActivity;.removeStickyBroadcast:(Landroid/content/Intent;)V", " Lcom/heyzap/internal/ProxyActivity;.bindService:(Landroid/content/Intent;Landroid/content/ServiceConnection;I)Z 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_0", "com.aim.racing-20046.apk", "game", "developer9", "Landroid/os/Handler;.obtainMessage:(ILjava/lang/Object;)Landroid/os/Message;", " Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I 2");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_0", "com.aim.racing-20046.apk", "game", "developer9", "Lcom/heyzap/internal/ProxyActivity;.startIntentSender:(Landroid/content/IntentSender;Landroid/content/Intent;IIILandroid/os/Bundle;)V", " Lcom/heyzap/internal/ProxyActivity;.sendStickyBroadcast:(Landroid/content/Intent;)V 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_0", "com.aim.racing-20046.apk", "game", "developer9", "Lcom/heyzap/internal/ProxyActivity;.stopService:(Landroid/content/Intent;)Z", " Lcom/heyzap/internal/ProxyActivity;.sendStickyOrderedBroadcast:(Landroid/content/Intent;Landroid/content/BroadcastReceiver;Landroid/os/Handler;ILjava/lang/String;Landroid/os/Bundle;)V 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_0", "com.aim.racing-20046.apk", "game", "developer9", "Lcom/heyzap/internal/ProxyActivity;.startIntentSender:(Landroid/content/IntentSender;Landroid/content/Intent;IIILandroid/os/Bundle;)V", " Lcom/heyzap/internal/ProxyActivity;.startActivityForResult:(Landroid/content/Intent;I)V 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.bigduckgames.flow-32.apk", "game", "developer10", "Lcom/noodlecake/noodlenews/NoodlecakeGameActivity;.onActivityResult:(IILandroid/content/Intent;)V", " Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I 2");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.bigduckgames.flow-32.apk", "game", "developer10", "Landroid/content/pm/PackageManager;.queryBroadcastReceivers:(Landroid/content/Intent;I)Ljava/util/List;", " Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.bigduckgames.flow-32.apk", "game", "developer10", "Landroid/content/pm/PackageManager;.queryBroadcastReceivers:(Landroid/content/Intent;I)Ljava/util/List;", " Landroid/util/Log;.i:(Ljava/lang/String;Ljava/lang/String;)I 2");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.bigduckgames.flow-32.apk", "game", "developer10", "Lcom/noodlecake/noodlenews/NoodlecakeGameActivity;.onActivityResult:(IILandroid/content/Intent;)V", " Landroid/util/Log;.e:(Ljava/lang/String;Ljava/lang/String;)I 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.bigduckgames.flow-32.apk", "game", "developer10", "Lcom/noodlecake/noodlenews/NoodlecakeGameActivity;.onActivityResult:(IILandroid/content/Intent;)V", " Landroid/util/Log;.e:(Ljava/lang/String;Ljava/lang/String;)I 2");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.bigduckgames.flow-32.apk", "game", "developer10", "Lcom/noodlecake/noodlenews/NoodlecakeGameActivity;.onActivityResult:(IILandroid/content/Intent;)V", " Landroid/util/Log;.e:(Ljava/lang/String;Ljava/lang/String;)I 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.bigduckgames.flow-32.apk", "game", "developer10", "Lcom/noodlecake/noodlenews/NoodlecakeGameActivity;.onActivityResult:(IILandroid/content/Intent;)V", " Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I 2");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.bigduckgames.flow-32.apk", "game", "developer10", "Landroid/content/pm/PackageManager;.queryBroadcastReceivers:(Landroid/content/Intent;I)Ljava/util/List;", " Ljava/io/Writer;.write:(Ljava/lang/String;)V 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.bigduckgames.flow-32.apk", "game", "developer10", "Landroid/content/pm/PackageManager;.queryBroadcastReceivers:(Landroid/content/Intent;I)Ljava/util/List;", " Landroid/util/Log;.i:(Ljava/lang/String;Ljava/lang/String;)I 2");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.bigduckgames.flow-32.apk", "game", "developer10", "Lcom/noodlecake/noodlenews/NoodlecakeGameActivity;.onActivityResult:(IILandroid/content/Intent;)V", " Landroid/util/Log;.i:(Ljava/lang/String;Ljava/lang/String;)I 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.bigduckgames.flow-32.apk", "game", "developer10", "Lcom/noodlecake/noodlenews/NoodlecakeGameActivity;.onActivityResult:(IILandroid/content/Intent;)V", " Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.bigduckgames.flow-32.apk", "game", "developer10", "Landroid/content/pm/PackageManager;.queryBroadcastReceivers:(Landroid/content/Intent;I)Ljava/util/List;", " Landroid/content/SharedPreferences$Editor?;.putString:(Ljava/lang/String;Ljava/lang/String;)Landroid/content/SharedPreferences$Editor; 2");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.bigduckgames.flow-32.apk", "game", "developer10", "Landroid/content/pm/PackageManager;.queryBroadcastReceivers:(Landroid/content/Intent;I)Ljava/util/List;", " Landroid/util/Log;.e:(Ljava/lang/String;Ljava/lang/String;)I 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.bigduckgames.flow-32.apk", "game", "developer10", "Landroid/content/pm/PackageManager;.queryBroadcastReceivers:(Landroid/content/Intent;I)Ljava/util/List;", " Landroid/content/ContextWrapper;.sendBroadcast:(Landroid/content/Intent;)V 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.bigduckgames.flow-32.apk", "game", "developer10", "Lcom/noodlecake/noodlenews/NoodlecakeGameActivity;.onActivityResult:(IILandroid/content/Intent;)V", " Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I 2");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.bigduckgames.flow-32.apk", "game", "developer10", "Lcom/noodlecake/noodlenews/NoodlecakeGameActivity;.onActivityResult:(IILandroid/content/Intent;)V", " Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.bigduckgames.flow-32.apk", "game", "developer10", "Lcom/noodlecake/noodlenews/NoodlecakeGameActivity;.onActivityResult:(IILandroid/content/Intent;)V", " Landroid/util/Log;.i:(Ljava/lang/String;Ljava/lang/String;)I 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.bigduckgames.flow-32.apk", "game", "developer10", "Lcom/noodlecake/noodlenews/NoodlecakeGameActivity;.onActivityResult:(IILandroid/content/Intent;)V", " Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.bigduckgames.flow-32.apk", "game", "developer10", "Lcom/noodlecake/noodlenews/NoodlecakeGameActivity;.onActivityResult:(IILandroid/content/Intent;)V", " Landroid/util/Log;.e:(Ljava/lang/String;Ljava/lang/String;)I 2");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.bigduckgames.flow-32.apk", "game", "developer10", "Lcom/noodlecake/noodlenews/NoodlecakeGameActivity;.onActivityResult:(IILandroid/content/Intent;)V", " Landroid/util/Log;.e:(Ljava/lang/String;Ljava/lang/String;)I 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.bigduckgames.flow-32.apk", "game", "developer10", "Lcom/noodlecake/noodlenews/NoodlecakeGameActivity;.onActivityResult:(IILandroid/content/Intent;)V", " Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.bigduckgames.flow-32.apk", "game", "developer10", "Lcom/noodlecake/noodlenews/NoodlecakeGameActivity;.onActivityResult:(IILandroid/content/Intent;)V", " Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.bigduckgames.flow-32.apk", "game", "developer10", "Lcom/noodlecake/noodlenews/NoodlecakeGameActivity;.onActivityResult:(IILandroid/content/Intent;)V", " Landroid/util/Log;.e:(Ljava/lang/String;Ljava/lang/String;)I 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.bigduckgames.flow-32.apk", "game", "developer10", "Lcom/noodlecake/noodlenews/NoodlecakeGameActivity;.onActivityResult:(IILandroid/content/Intent;)V", " Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.bigduckgames.flow-32.apk", "game", "developer10", "Lcom/noodlecake/noodlenews/NoodlecakeGameActivity;.onActivityResult:(IILandroid/content/Intent;)V", " Landroid/util/Log;.e:(Ljava/lang/String;Ljava/lang/String;)I 2");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.bigduckgames.flow-32.apk", "game", "developer10", "Lcom/noodlecake/noodlenews/NoodlecakeGameActivity;.onActivityResult:(IILandroid/content/Intent;)V", " Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.bigduckgames.flow-32.apk", "game", "developer10", "Lcom/noodlecake/noodlenews/NoodlecakeGameActivity;.onActivityResult:(IILandroid/content/Intent;)V", " Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.bigduckgames.flow-32.apk", "game", "developer10", "Lcom/noodlecake/noodlenews/NoodlecakeGameActivity;.onActivityResult:(IILandroid/content/Intent;)V", " Landroid/util/Log;.i:(Ljava/lang/String;Ljava/lang/String;)I 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.bigduckgames.flow-32.apk", "game", "developer10", "Lcom/noodlecake/noodlenews/NoodlecakeGameActivity;.onActivityResult:(IILandroid/content/Intent;)V", " Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.bigduckgames.flow-32.apk", "game", "developer10", "Lcom/noodlecake/noodlenews/NoodlecakeGameActivity;.onActivityResult:(IILandroid/content/Intent;)V", " Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I 2");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.bigduckgames.flow-32.apk", "game", "developer10", "Lcom/noodlecake/noodlenews/NoodlecakeGameActivity;.onActivityResult:(IILandroid/content/Intent;)V", " Landroid/util/Log;.i:(Ljava/lang/String;Ljava/lang/String;)I 2");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.bigduckgames.flow-32.apk", "game", "developer10", "Landroid/content/pm/PackageManager;.queryBroadcastReceivers:(Landroid/content/Intent;I)Ljava/util/List;", " Landroid/util/Log;.e:(Ljava/lang/String;Ljava/lang/String;)I 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.bigduckgames.flow-32.apk", "game", "developer10", "Lcom/noodlecake/noodlenews/NoodlecakeGameActivity;.onActivityResult:(IILandroid/content/Intent;)V", " Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I 2");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.bigduckgames.flow-32.apk", "game", "developer10", "Lcom/noodlecake/noodlenews/NoodlecakeGameActivity;.onActivityResult:(IILandroid/content/Intent;)V", " Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.bigduckgames.flow-32.apk", "game", "developer10", "Landroid/content/pm/PackageManager;.queryBroadcastReceivers:(Landroid/content/Intent;I)Ljava/util/List;", " Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.bigduckgames.flow-32.apk", "game", "developer10", "Lcom/noodlecake/noodlenews/NoodlecakeGameActivity;.onActivityResult:(IILandroid/content/Intent;)V", " Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.bigduckgames.flow-32.apk", "game", "developer10", "Lcom/noodlecake/noodlenews/NoodlecakeGameActivity;.onActivityResult:(IILandroid/content/Intent;)V", " Landroid/util/Log;.e:(Ljava/lang/String;Ljava/lang/String;)I 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.bigduckgames.flow-32.apk", "game", "developer10", "Lcom/noodlecake/noodlenews/NoodlecakeGameActivity;.onActivityResult:(IILandroid/content/Intent;)V", " Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.bigduckgames.flow-32.apk", "game", "developer10", "Lcom/noodlecake/noodlenews/NoodlecakeGameActivity;.onActivityResult:(IILandroid/content/Intent;)V", " Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.bigduckgames.flow-32.apk", "game", "developer10", "Lcom/noodlecake/noodlenews/NoodlecakeGameActivity;.onActivityResult:(IILandroid/content/Intent;)V", " Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I 2");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.bigduckgames.flow-32.apk", "game", "developer10", "Lcom/noodlecake/noodlenews/NoodlecakeGameActivity;.onActivityResult:(IILandroid/content/Intent;)V", " Landroid/util/Log;.e:(Ljava/lang/String;Ljava/lang/String;)I 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.bigduckgames.flow-32.apk", "game", "developer10", "Lcom/noodlecake/noodlenews/NoodlecakeGameActivity;.onActivityResult:(IILandroid/content/Intent;)V", " Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.bigduckgames.flow-32.apk", "game", "developer10", "Landroid/content/pm/PackageManager;.queryBroadcastReceivers:(Landroid/content/Intent;I)Ljava/util/List;", " Landroid/util/Log;.i:(Ljava/lang/String;Ljava/lang/String;)I 2");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.bigduckgames.flow-32.apk", "game", "developer10", "Landroid/content/pm/PackageManager;.queryBroadcastReceivers:(Landroid/content/Intent;I)Ljava/util/List;", " Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I 2");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.bigduckgames.flow-32.apk", "game", "developer10", "Lcom/noodlecake/noodlenews/NoodlecakeGameActivity;.onActivityResult:(IILandroid/content/Intent;)V", " Landroid/util/Log;.e:(Ljava/lang/String;Ljava/lang/String;)I 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.bigduckgames.flow-32.apk", "game", "developer10", "Lcom/noodlecake/noodlenews/NoodlecakeGameActivity;.onActivityResult:(IILandroid/content/Intent;)V", " Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I 2");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.bigduckgames.flow-32.apk", "game", "developer10", "Lcom/noodlecake/noodlenews/NoodlecakeGameActivity;.onActivityResult:(IILandroid/content/Intent;)V", " Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.bigduckgames.flow-32.apk", "game", "developer10", "Lcom/noodlecake/noodlenews/NoodlecakeGameActivity;.onActivityResult:(IILandroid/content/Intent;)V", " Landroid/util/Log;.i:(Ljava/lang/String;Ljava/lang/String;)I 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.bigduckgames.flow-32.apk", "game", "developer10", "Landroid/content/pm/PackageManager;.queryBroadcastReceivers:(Landroid/content/Intent;I)Ljava/util/List;", " Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.bigduckgames.flow-32.apk", "game", "developer10", "Lcom/noodlecake/noodlenews/NoodlecakeGameActivity;.onActivityResult:(IILandroid/content/Intent;)V", " Landroid/util/Log;.i:(Ljava/lang/String;Ljava/lang/String;)I 2");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.bigduckgames.flow-32.apk", "game", "developer10", "Landroid/content/pm/PackageManager;.queryBroadcastReceivers:(Landroid/content/Intent;I)Ljava/util/List;", " Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.bigduckgames.flow-32.apk", "game", "developer10", "Lcom/noodlecake/noodlenews/NoodlecakeGameActivity;.onActivityResult:(IILandroid/content/Intent;)V", " Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I 2");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.bigduckgames.flow-32.apk", "game", "developer10", "Landroid/content/pm/PackageManager;.queryBroadcastReceivers:(Landroid/content/Intent;I)Ljava/util/List;", " Landroid/util/Log;.i:(Ljava/lang/String;Ljava/lang/String;)I 2");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.bigduckgames.flow-32.apk", "game", "developer10", "Landroid/content/pm/PackageManager;.queryBroadcastReceivers:(Landroid/content/Intent;I)Ljava/util/List;", " Landroid/content/SharedPreferences$Editor?;.putString:(Ljava/lang/String;Ljava/lang/String;)Landroid/content/SharedPreferences$Editor; 2");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.bigduckgames.flow-32.apk", "game", "developer10", "Lcom/noodlecake/noodlenews/NoodlecakeGameActivity;.onActivityResult:(IILandroid/content/Intent;)V", " Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.bigduckgames.flow-32.apk", "game", "developer10", "Lcom/noodlecake/noodlenews/NoodlecakeGameActivity;.onActivityResult:(IILandroid/content/Intent;)V", " Landroid/util/Log;.i:(Ljava/lang/String;Ljava/lang/String;)I 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.bigduckgames.flow-32.apk", "game", "developer10", "Landroid/content/pm/PackageManager;.queryBroadcastReceivers:(Landroid/content/Intent;I)Ljava/util/List;", " Landroid/util/Log;.e:(Ljava/lang/String;Ljava/lang/String;)I 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.bigduckgames.flow-32.apk", "game", "developer10", "Lcom/noodlecake/noodlenews/NoodlecakeGameActivity;.onActivityResult:(IILandroid/content/Intent;)V", " Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I 2");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.bigduckgames.flow-32.apk", "game", "developer10", "Lcom/noodlecake/noodlenews/NoodlecakeGameActivity;.onActivityResult:(IILandroid/content/Intent;)V", " Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I 2");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.bigduckgames.flow-32.apk", "game", "developer10", "Lcom/noodlecake/noodlenews/NoodlecakeGameActivity;.onActivityResult:(IILandroid/content/Intent;)V", " Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.bigduckgames.flow-32.apk", "game", "developer10", "Lcom/noodlecake/noodlenews/NoodlecakeGameActivity;.onActivityResult:(IILandroid/content/Intent;)V", " Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.bigduckgames.flow-32.apk", "game", "developer10", "Landroid/content/pm/PackageManager;.queryBroadcastReceivers:(Landroid/content/Intent;I)Ljava/util/List;", " Landroid/content/SharedPreferences$Editor?;.putString:(Ljava/lang/String;Ljava/lang/String;)Landroid/content/SharedPreferences$Editor; 2");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.bigduckgames.flow-32.apk", "game", "developer10", "Landroid/content/pm/PackageManager;.queryBroadcastReceivers:(Landroid/content/Intent;I)Ljava/util/List;", " Landroid/util/Log;.e:(Ljava/lang/String;Ljava/lang/String;)I 2");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.bigduckgames.flow-32.apk", "game", "developer10", "Lcom/noodlecake/noodlenews/NoodlecakeGameActivity;.onActivityResult:(IILandroid/content/Intent;)V", " Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I 2");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.bigduckgames.flow-32.apk", "game", "developer10", "Lcom/noodlecake/noodlenews/NoodlecakeGameActivity;.onActivityResult:(IILandroid/content/Intent;)V", " Landroid/util/Log;.e:(Ljava/lang/String;Ljava/lang/String;)I 2");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.bigduckgames.flow-32.apk", "game", "developer10", "Landroid/content/pm/PackageManager;.queryBroadcastReceivers:(Landroid/content/Intent;I)Ljava/util/List;", " Landroid/util/Log;.i:(Ljava/lang/String;Ljava/lang/String;)I 2");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.bigduckgames.flow-32.apk", "game", "developer10", "Lcom/noodlecake/noodlenews/NoodlecakeGameActivity;.onActivityResult:(IILandroid/content/Intent;)V", " Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I 2");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.bigduckgames.flow-32.apk", "game", "developer10", "Landroid/content/pm/PackageManager;.queryBroadcastReceivers:(Landroid/content/Intent;I)Ljava/util/List;", " Landroid/util/Log;.e:(Ljava/lang/String;Ljava/lang/String;Ljava/lang/Throwable;)I 2");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.bigduckgames.flow-32.apk", "game", "developer10", "Landroid/content/pm/PackageManager;.queryBroadcastReceivers:(Landroid/content/Intent;I)Ljava/util/List;", " Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.bigduckgames.flow-32.apk", "game", "developer10", "Lcom/noodlecake/noodlenews/NoodlecakeGameActivity;.onActivityResult:(IILandroid/content/Intent;)V", " Landroid/util/Log;.e:(Ljava/lang/String;Ljava/lang/String;)I 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.bigduckgames.flow-32.apk", "game", "developer10", "Lcom/noodlecake/noodlenews/NoodlecakeGameActivity;.onActivityResult:(IILandroid/content/Intent;)V", " Landroid/util/Log;.i:(Ljava/lang/String;Ljava/lang/String;)I 1");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
