var getdata = contract.set.getData("secu_com_2", "com.affimity-16.apk", "social", "developer04", "Landroid/content/pm/PackageManager;.queryBroadcastReceivers:(Landroid/content/Intent;I)Ljava/util/List;", "Landroid/util/Log;.i:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_2", "com.affimity-16.apk", "social", "developer04", "Landroid/content/pm/PackageManager;.queryBroadcastReceivers:(Landroid/content/Intent;I)Ljava/util/List;", "Landroid/content/SharedPreferences$Editor?;.putString:(Ljava/lang/String;Ljava/lang/String;)Landroid/content/SharedPreferences$Editor;");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_2", "com.affimity-16.apk", "social", "developer04", "Landroid/content/pm/PackageManager;.queryBroadcastReceivers:(Landroid/content/Intent;I)Ljava/util/List;", "Landroid/content/SharedPreferences$Editor?;.putString:(Ljava/lang/String;Ljava/lang/String;)Landroid/content/SharedPreferences$Editor;");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_2", "com.affimity-16.apk", "social", "developer04", "Ljava/net/URLConnection;.getInputStream:()Ljava/io/InputStream;", "Ljava/io/FileOutputStream;.write:([BII)V");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_2", "com.affimity-16.apk", "social", "developer04", "Ljava/net/URLConnection;.getInputStream:()Ljava/io/InputStream;", "Ljava/io/ByteArrayOutputStream;.write:([BII)V");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_2", "com.affimity-16.apk", "social", "developer04", "Landroid/content/pm/PackageManager;.queryBroadcastReceivers:(Landroid/content/Intent;I)Ljava/util/List;", "Landroid/content/ContextWrapper;.sendBroadcast:(Landroid/content/Intent;)V");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_2", "com.affimity-16.apk", "social", "developer04", "Landroid/content/pm/PackageManager;.queryBroadcastReceivers:(Landroid/content/Intent;I)Ljava/util/List;", "Landroid/util/Log;.i:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_2", "com.affimity-16.apk", "social", "developer04", "Lorg/apache/http/HttpResponse;.getEntity:()Lorg/apache/http/HttpEntity;", "Lcom/android/volley/toolbox/PoolingByteArrayOutputStream;.write:([BII)V");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_2", "com.affimity-16.apk", "social", "developer04", "Lorg/apache/http/HttpResponse;.getEntity:()Lorg/apache/http/HttpEntity;", "Lcom/android/volley/toolbox/PoolingByteArrayOutputStream;.write:([BII)V");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_2", "com.affimity-16.apk", "social", "developer04", "Lorg/apache/http/HttpResponse;.getEntity:()Lorg/apache/http/HttpEntity;", "Ljava/io/ByteArrayOutputStream;.write:([BII)V");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_2", "com.affimity-16.apk", "social", "developer04", "Lcom/affimity/twitter/TwitterMainActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/content/SharedPreferences$Editor?;.putString:(Ljava/lang/String;Ljava/lang/String;)Landroid/content/SharedPreferences$Editor;");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_2", "com.affimity-16.apk", "social", "developer04", "Lorg/apache/http/HttpResponse;.getEntity:()Lorg/apache/http/HttpEntity;", "Ljava/io/ByteArrayOutputStream;.write:([BII)V");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_2", "com.affimity-16.apk", "social", "developer04", "Landroid/content/pm/PackageManager;.queryBroadcastReceivers:(Landroid/content/Intent;I)Ljava/util/List;", "Landroid/content/SharedPreferences$Editor?;.putString:(Ljava/lang/String;Ljava/lang/String;)Landroid/content/SharedPreferences$Editor;");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_0", "com.asiandate-21.apk", "social", "developer05", "Landroid/content/pm/PackageManager;.queryBroadcastReceivers:(Landroid/content/Intent;I)Ljava/util/List;", "Landroid/content/ContextWrapper;.sendBroadcast:(Landroid/content/Intent;)V");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_0", "com.asiandate-21.apk", "social", "developer05", "Landroid/content/pm/PackageManager;.queryBroadcastReceivers:(Landroid/content/Intent;I)Ljava/util/List;", "Landroid/util/Log;.i:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_0", "com.asiandate-21.apk", "social", "developer05", "Landroid/content/pm/PackageManager;.queryBroadcastReceivers:(Landroid/content/Intent;I)Ljava/util/List;", "Ljava/io/Writer;.write:(Ljava/lang/String;)V");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_0", "com.asiandate-21.apk", "social", "developer05", "Landroid/content/pm/PackageManager;.queryBroadcastReceivers:(Landroid/content/Intent;I)Ljava/util/List;", "Landroid/util/Log;.i:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_0", "com.asiandate-21.apk", "social", "developer05", "Landroid/content/pm/PackageManager;.queryBroadcastReceivers:(Landroid/content/Intent;I)Ljava/util/List;", "Landroid/content/SharedPreferences$Editor?;.putString:(Ljava/lang/String;Ljava/lang/String;)Landroid/content/SharedPreferences$Editor;");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_0", "com.asiandate-21.apk", "social", "developer05", "Landroid/content/pm/PackageManager;.queryBroadcastReceivers:(Landroid/content/Intent;I)Ljava/util/List;", "Landroid/util/Log;.e:(Ljava/lang/String;Ljava/lang/String;Ljava/lang/Throwable;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_0", "com.asiandate-21.apk", "social", "developer05", "Landroid/content/pm/PackageManager;.queryBroadcastReceivers:(Landroid/content/Intent;I)Ljava/util/List;", "Landroid/util/Log;.i:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_0", "com.asiandate-21.apk", "social", "developer05", "Landroid/content/pm/PackageManager;.queryBroadcastReceivers:(Landroid/content/Intent;I)Ljava/util/List;", "Landroid/util/Log;.i:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_0", "com.asiandate-21.apk", "social", "developer05", "Landroid/content/pm/PackageManager;.queryBroadcastReceivers:(Landroid/content/Intent;I)Ljava/util/List;", "Landroid/content/SharedPreferences$Editor?;.putString:(Ljava/lang/String;Ljava/lang/String;)Landroid/content/SharedPreferences$Editor;");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_0", "com.asiandate-21.apk", "social", "developer05", "Landroid/content/pm/PackageManager;.queryBroadcastReceivers:(Landroid/content/Intent;I)Ljava/util/List;", "Landroid/util/Log;.i:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_0", "com.asiandate-21.apk", "social", "developer05", "Landroid/content/pm/PackageManager;.queryBroadcastReceivers:(Landroid/content/Intent;I)Ljava/util/List;", "Landroid/content/SharedPreferences$Editor?;.putString:(Ljava/lang/String;Ljava/lang/String;)Landroid/content/SharedPreferences$Editor;");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/tools/Common$9;.onLocationChanged:(Landroid/location/Location;)V", "Landroid/content/SharedPreferences$Editor?;.putString:(Ljava/lang/String;Ljava/lang/String;)Landroid/content/SharedPreferences$Editor;");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.i:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Landroid/app/Activity;.findViewById:(I)Landroid/view/View;", "Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Landroid/app/Activity;.findViewById:(I)Landroid/view/View;", "Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Landroid/location/LocationManager;.getLastKnownLocation:(Ljava/lang/String;)Landroid/location/Location;", "Landroid/content/SharedPreferences$Editor?;.putString:(Ljava/lang/String;Ljava/lang/String;)Landroid/content/SharedPreferences$Editor;");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.e:(Ljava/lang/String;Ljava/lang/String;Ljava/lang/Throwable;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.i:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Landroid/app/Activity;.findViewById:(I)Landroid/view/View;", "Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.i:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/content/SharedPreferences$Editor?;.putString:(Ljava/lang/String;Ljava/lang/String;)Landroid/content/SharedPreferences$Editor;");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.i:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.e:(Ljava/lang/String;Ljava/lang/String;Ljava/lang/Throwable;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.e:(Ljava/lang/String;Ljava/lang/String;Ljava/lang/Throwable;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.i:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/content/SharedPreferences$Editor?;.putString:(Ljava/lang/String;Ljava/lang/String;)Landroid/content/SharedPreferences$Editor;");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.e:(Ljava/lang/String;Ljava/lang/String;Ljava/lang/Throwable;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.e:(Ljava/lang/String;Ljava/lang/String;Ljava/lang/Throwable;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Landroid/app/Activity;.findViewById:(I)Landroid/view/View;", "Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/content/SharedPreferences$Editor?;.putString:(Ljava/lang/String;Ljava/lang/String;)Landroid/content/SharedPreferences$Editor;");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Landroid/location/LocationManager;.getLastKnownLocation:(Ljava/lang/String;)Landroid/location/Location;", "Landroid/content/SharedPreferences$Editor?;.putString:(Ljava/lang/String;Ljava/lang/String;)Landroid/content/SharedPreferences$Editor;");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.i:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Landroid/app/Activity;.findViewById:(I)Landroid/view/View;", "Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Landroid/location/LocationManager;.getLastKnownLocation:(Ljava/lang/String;)Landroid/location/Location;", "Landroid/content/SharedPreferences$Editor?;.putString:(Ljava/lang/String;Ljava/lang/String;)Landroid/content/SharedPreferences$Editor;");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.i:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.i:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.i:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.i:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/content/SharedPreferences$Editor?;.putString:(Ljava/lang/String;Ljava/lang/String;)Landroid/content/SharedPreferences$Editor;");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/content/SharedPreferences$Editor?;.putString:(Ljava/lang/String;Ljava/lang/String;)Landroid/content/SharedPreferences$Editor;");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.i:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/content/SharedPreferences$Editor?;.putBoolean:(Ljava/lang/String;Z)Landroid/content/SharedPreferences$Editor;");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Landroid/app/Activity;.findViewById:(I)Landroid/view/View;", "Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/content/SharedPreferences$Editor?;.putString:(Ljava/lang/String;Ljava/lang/String;)Landroid/content/SharedPreferences$Editor;");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Landroid/app/Activity;.findViewById:(I)Landroid/view/View;", "Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.i:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.i:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Landroid/app/Activity;.findViewById:(I)Landroid/view/View;", "Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.e:(Ljava/lang/String;Ljava/lang/String;Ljava/lang/Throwable;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/tools/Common$9;.onLocationChanged:(Landroid/location/Location;)V", "Landroid/content/SharedPreferences$Editor?;.putString:(Ljava/lang/String;Ljava/lang/String;)Landroid/content/SharedPreferences$Editor;");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/content/SharedPreferences$Editor?;.putLong:(Ljava/lang/String;J)Landroid/content/SharedPreferences$Editor;");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Landroid/app/Activity;.findViewById:(I)Landroid/view/View;", "Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.e:(Ljava/lang/String;Ljava/lang/String;Ljava/lang/Throwable;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.i:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.e:(Ljava/lang/String;Ljava/lang/String;Ljava/lang/Throwable;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.i:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.e:(Ljava/lang/String;Ljava/lang/String;Ljava/lang/Throwable;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.e:(Ljava/lang/String;Ljava/lang/String;Ljava/lang/Throwable;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.e:(Ljava/lang/String;Ljava/lang/String;Ljava/lang/Throwable;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.e:(Ljava/lang/String;Ljava/lang/String;Ljava/lang/Throwable;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.i:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/content/SharedPreferences$Editor?;.putString:(Ljava/lang/String;Ljava/lang/String;)Landroid/content/SharedPreferences$Editor;");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.i:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.e:(Ljava/lang/String;Ljava/lang/String;Ljava/lang/Throwable;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Landroid/app/Activity;.findViewById:(I)Landroid/view/View;", "Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.e:(Ljava/lang/String;Ljava/lang/String;Ljava/lang/Throwable;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Landroid/location/LocationManager;.getLastKnownLocation:(Ljava/lang/String;)Landroid/location/Location;", "Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/tools/Common$9;.onLocationChanged:(Landroid/location/Location;)V", "Landroid/content/SharedPreferences$Editor?;.putString:(Ljava/lang/String;Ljava/lang/String;)Landroid/content/SharedPreferences$Editor;");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.e:(Ljava/lang/String;Ljava/lang/String;Ljava/lang/Throwable;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.e:(Ljava/lang/String;Ljava/lang/String;Ljava/lang/Throwable;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.e:(Ljava/lang/String;Ljava/lang/String;Ljava/lang/Throwable;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Landroid/location/LocationManager;.getLastKnownLocation:(Ljava/lang/String;)Landroid/location/Location;", "Landroid/content/SharedPreferences$Editor?;.putString:(Ljava/lang/String;Ljava/lang/String;)Landroid/content/SharedPreferences$Editor;");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.e:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.e:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.e:(Ljava/lang/String;Ljava/lang/String;Ljava/lang/Throwable;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.e:(Ljava/lang/String;Ljava/lang/String;Ljava/lang/Throwable;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.i:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Landroid/location/LocationManager;.getLastKnownLocation:(Ljava/lang/String;)Landroid/location/Location;", "Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.i:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.i:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.i:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.i:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.e:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.i:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Landroid/app/Activity;.findViewById:(I)Landroid/view/View;", "Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.e:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.i:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.i:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Landroid/location/LocationManager;.getLastKnownLocation:(Ljava/lang/String;)Landroid/location/Location;", "Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Landroid/app/Activity;.findViewById:(I)Landroid/view/View;", "Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Ljava/io/Writer;.write:(Ljava/lang/String;)V");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Landroid/app/Activity;.findViewById:(I)Landroid/view/View;", "Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.i:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Landroid/app/Activity;.findViewById:(I)Landroid/view/View;", "Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Landroid/app/Activity;.findViewById:(I)Landroid/view/View;", "Landroid/util/Log;.i:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.e:(Ljava/lang/String;Ljava/lang/String;Ljava/lang/Throwable;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.e:(Ljava/lang/String;Ljava/lang/String;Ljava/lang/Throwable;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/content/SharedPreferences$Editor?;.putString:(Ljava/lang/String;Ljava/lang/String;)Landroid/content/SharedPreferences$Editor;");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.i:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Landroid/app/Activity;.findViewById:(I)Landroid/view/View;", "Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.i:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.e:(Ljava/lang/String;Ljava/lang/String;Ljava/lang/Throwable;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.e:(Ljava/lang/String;Ljava/lang/String;Ljava/lang/Throwable;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.e:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.i:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/content/SharedPreferences$Editor?;.putString:(Ljava/lang/String;Ljava/lang/String;)Landroid/content/SharedPreferences$Editor;");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.e:(Ljava/lang/String;Ljava/lang/String;Ljava/lang/Throwable;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.e:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.i:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.e:(Ljava/lang/String;Ljava/lang/String;Ljava/lang/Throwable;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.i:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/tools/Common$9;.onLocationChanged:(Landroid/location/Location;)V", "Landroid/content/SharedPreferences$Editor?;.putString:(Ljava/lang/String;Ljava/lang/String;)Landroid/content/SharedPreferences$Editor;");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Landroid/app/Activity;.findViewById:(I)Landroid/view/View;", "Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.i:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Landroid/location/LocationManager;.getLastKnownLocation:(Ljava/lang/String;)Landroid/location/Location;", "Landroid/content/SharedPreferences$Editor?;.putString:(Ljava/lang/String;Ljava/lang/String;)Landroid/content/SharedPreferences$Editor;");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Landroid/location/LocationManager;.getLastKnownLocation:(Ljava/lang/String;)Landroid/location/Location;", "Landroid/content/SharedPreferences$Editor?;.putString:(Ljava/lang/String;Ljava/lang/String;)Landroid/content/SharedPreferences$Editor;");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Landroid/app/Activity;.findViewById:(I)Landroid/view/View;", "Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.e:(Ljava/lang/String;Ljava/lang/String;Ljava/lang/Throwable;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.i:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.e:(Ljava/lang/String;Ljava/lang/String;Ljava/lang/Throwable;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Landroid/app/Activity;.findViewById:(I)Landroid/view/View;", "Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.i:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/content/SharedPreferences$Editor?;.putString:(Ljava/lang/String;Ljava/lang/String;)Landroid/content/SharedPreferences$Editor;");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.i:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.e:(Ljava/lang/String;Ljava/lang/String;Ljava/lang/Throwable;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Landroid/location/LocationManager;.getLastKnownLocation:(Ljava/lang/String;)Landroid/location/Location;", "Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/content/SharedPreferences$Editor?;.putString:(Ljava/lang/String;Ljava/lang/String;)Landroid/content/SharedPreferences$Editor;");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.i:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.e:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.i:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.e:(Ljava/lang/String;Ljava/lang/String;Ljava/lang/Throwable;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.d:(Ljava/lang/String;Ljava/lang/String;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
var getdata = contract.set.getData("secu_com_1", "com.choiceoflove.dating-38.apk", "social", "developer06", "Lcom/choiceoflove/dating/LauncherActivity;.onActivityResult:(IILandroid/content/Intent;)V", "Landroid/util/Log;.e:(Ljava/lang/String;Ljava/lang/String;Ljava/lang/Throwable;)I");
var reciept = web3.eth.sendTransaction({ from: defaultAddr, to: contractAddr, data: getdata, gas: 7000000 });
console.log(reciept);
